server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BANKING-PROJECT-INNOVAPATIKA
          uri: lb://BANKING-PROJECT-INNOVAPATIKA
          predicates:
            - Path=/api/customer/**
      globalcors:
        cors-configurations:
          allowedMethods:
            - POST
            - PUT

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost


